spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vkusoru
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
recipelist:
  basePath: http://vkuso.ru/recipes/
  lastPage: 408